// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_hpnl_core_RdmService */

#ifndef _Included_com_intel_hpnl_core_RdmService
#define _Included_com_intel_hpnl_core_RdmService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_hpnl_core_RdmService
 * Method:    init
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_com_intel_hpnl_core_RdmService_init
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_intel_hpnl_core_RdmService
 * Method:    listen
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT jint JNICALL Java_com_intel_hpnl_core_RdmService_listen
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_intel_hpnl_core_RdmService
 * Method:    get_con
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_hpnl_core_RdmService_get_1con
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_intel_hpnl_core_RdmService
 * Method:    wait_event
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_hpnl_core_RdmService_wait_1event
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_hpnl_core_RdmService
 * Method:    set_buffer
 * Signature: (Ljava/nio/ByteBuffer;JIJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_RdmService_set_1buffer1
  (JNIEnv *, jobject, jobject, jlong, jint, jlong);

/*
 * Class:     com_intel_hpnl_core_RdmService
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_RdmService_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
