/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_hpnl_core_EqService */

#ifndef _Included_com_intel_hpnl_core_EqService
#define _Included_com_intel_hpnl_core_EqService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    connect
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_hpnl_core_EqService_connect
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    wait_eq_event
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_hpnl_core_EqService_wait_1eq_1event
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    add_eq_event
 * Signature: (j)I
 */
JNIEXPORT jint JNICALL Java_com_intel_hpnl_core_EqService_add_1eq_1event
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    delete_eq_event
 * Signature: (j)I
 */
JNIEXPORT jint JNICALL Java_com_intel_hpnl_core_EqService_delete_1eq_1event
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    shutdown
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_EqService_shutdown
  (JNIEnv *, jobject, jlong);


/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    set_recv_buffer
 * Signature: (Ljava/nio/ByteBuffer;JI)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_EqService_set_1recv_1buffer
  (JNIEnv *, jobject, jobject, jlong, jint);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    set_send_buffer
 * Signature: (Ljava/nio/ByteBuffer;JI)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_EqService_set_1send_1buffer
  (JNIEnv *, jobject, jobject, jlong, jint);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    reg_rma_buffer
 * Signature: (Ljava/nio/ByteBuffer;JI)V
 */
JNIEXPORT jlong JNICALL Java_com_intel_hpnl_core_EqService_reg_1rma_1buffer
  (JNIEnv *, jobject, jobject, jlong, jint);

JNIEXPORT jlong JNICALL Java_com_intel_hpnl_core_EqService_reg_1rma_1buffer_1by_1address
  (JNIEnv *, jobject, jlong, jlong, jint);

JNIEXPORT void JNICALL Java_com_intel_hpnl_core_EqService_unreg_1rma_1buffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    get_buffer_address
 * Signature: (Ljava/nio/ByteBuffer)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_hpnl_core_EqService_get_1buffer_1address
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_EqService_init
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_EqService_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_EqService_free
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
