/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_hpnl_core_MsgConnection */

#ifndef _Included_com_intel_hpnl_core_MsgConnection
#define _Included_com_intel_hpnl_core_MsgConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_hpnl_core_MsgConnection
 * Method:    recv
 * Signature: (Ljava/nio/ByteBuffer;IJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_MsgConnection_recv
  (JNIEnv *, jobject, jobject, jint, jlong);

/*
 * Class:     com_intel_hpnl_core_MsgConnection
 * Method:    send
 * Signature: (IIJ)I
 */
JNIEXPORT jint JNICALL Java_com_intel_hpnl_core_MsgConnection_send
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     com_intel_hpnl_core_MsgConnection
 * Method:    read
 * Signature: (IIJJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_intel_hpnl_core_MsgConnection_read
  (JNIEnv *, jobject, jint, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     com_intel_hpnl_core_MsgConnection
 * Method:    init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_MsgConnection_init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_hpnl_core_MsgConnection
 * Method:    get_cq_index
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_hpnl_core_MsgConnection_get_1cq_1index
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_hpnl_core_MsgConnection
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_MsgConnection_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_hpnl_core_MsgConnection
 * Method:    deleteGlobalRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_MsgConnection_deleteGlobalRef
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_hpnl_core_MsgConnection
 * Method:    releaseRecvBuffer
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_MsgConnection_releaseRecvBuffer
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_intel_hpnl_core_MsgConnection
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_MsgConnection_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
