/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_hpnl_core_Connection */

#ifndef _Included_com_intel_hpnl_core_Connection
#define _Included_com_intel_hpnl_core_Connection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_hpnl_core_Connection
 * Method:    recv
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_Connection_recv
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_intel_hpnl_core_Connection
 * Method:    send
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_Connection_send
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_intel_hpnl_core_Connection
 * Method:    init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_Connection_init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_hpnl_core_Connection
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_Connection_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
