/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_hpnl_core_EqService */

#ifndef _Included_com_intel_hpnl_core_EqService
#define _Included_com_intel_hpnl_core_EqService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    shutdown
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_EqService_shutdown1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    native_connect
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_hpnl_core_EqService_native_1connect
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    wait_eq_event
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_hpnl_core_EqService_wait_1eq_1event1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    add_eq_event
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_intel_hpnl_core_EqService_add_1eq_1event
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    delete_eq_event
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_intel_hpnl_core_EqService_delete_1eq_1event1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    set_buffer
 * Signature: (Ljava/nio/ByteBuffer;JIJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_EqService_set_1buffer1
  (JNIEnv *, jobject, jobject, jlong, jint, jlong);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    reg_rma_buffer
 * Signature: (Ljava/nio/ByteBuffer;JIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_hpnl_core_EqService_reg_1rma_1buffer
  (JNIEnv *, jobject, jobject, jlong, jint, jlong);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    reg_rma_buffer_by_address
 * Signature: (JJIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_hpnl_core_EqService_reg_1rma_1buffer_1by_1address
  (JNIEnv *, jobject, jlong, jlong, jint, jlong);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    unreg_rma_buffer
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_EqService_unreg_1rma_1buffer
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    get_buffer_address
 * Signature: (Ljava/nio/ByteBuffer;J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_hpnl_core_EqService_get_1buffer_1address
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    init
 * Signature: (IIZ)I
 */
JNIEXPORT jint JNICALL Java_com_intel_hpnl_core_EqService_init
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_EqService_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_hpnl_core_EqService
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_EqService_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
