/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_hpnl_core_Utils */

#ifndef _Included_com_intel_hpnl_core_Utils
#define _Included_com_intel_hpnl_core_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_hpnl_core_Utils
 * Method:    set_affinity
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_hpnl_core_Utils_set_1affinity
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
