FROM fedora:27
MAINTAINER Haodong haodong.tang@intel.com
RUN dnf update -y
RUN dnf install -y java-1.8.0-openjdk git maven cmake boost-devel boost-system make automake gcc gcc-c++ kernel-devel libtool
RUN git clone https://github.com/ofiwg/libfabric.git; cd libfabric; git checkout -b v1.8.0 tags/v1.8.0; ./autogen.sh; ./configure --prefix=/usr/local --enable-sockets && make -j && make install
ENV LD_LIBRARY_PATH /usr/local/lib
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk
RUN ldconfig
RUN git clone https://github.com/tanghaodong25/HPNL.git
RUN cd HPNL; git submodule update --init --recursive
RUN cd HPNL; mkdir build && cd build; cmake -DWITH_JAVA=ON .. && make install -j && ctest
ARG MAVEN_OPTS
RUN cd HPNL/java/hpnl; mvn install